cuentas = {
    "1": "Activo",
    "11": "Activo corriente",
    "111": "Efectivo y Equivalente al Efectivo",
    "1111": "Caja",
    "1112": "Caja chica",
    "1113": "Bancos",
    "1114": "Depositos a Plazo (3 meses)",
    "1115": "Inversiones en Bonos (3 meses)",
    "112": "Inversiones",
    "1121": "Inversiones en Bonos (menor igual un anio)",
    "1122": "Depositos a Plazo (menor igual un anio)",
    "113": "Cuentas y Documentos Por cobrar",
    "1131": "Clientes",
    "11311": "Reservas para cuentas incobrables",
    "1132": "Deudores Varios",
    "1133": "Funcionarios y empleados",
    "1134": "Intereses por cobrar",
    "1135": "Impuestos diferidos por cobrar",
    "1136": "Rentas por cobrar",
    "1137": "Impuestos por cobrar",
    "1138": "Dividendos por cobrar",
    "1139": "Documentos por cobrar (menor igual a un anio)",
    "114": "Inventarios",
    "1141": "Empresas comerciales y servicios",
    "11411": "Inventario Inicial",
    "11412": "Inventario Final",
    "1142": "Empresas industriales",
    "11421": "Inventario de materia prima",
    "11422": "Inventario de productos en proceso",
    "11423": "Inventario de productos terminados",
    "115": "Pagos Anticipados",
    "1151": "Papeleria y Utiles",
    "1152": "Material de empaque",
    "1153": "Material de aseo",
    "1154": "Propaganda y Publicidad",
    "1155": "Anticipos a proveedor",
    "1156": "Rentas pagadas por anticipado",
    "1157": "Suscripciones pagadas por anticipado",
    "1158": "Intereses pagados por anticipado",
    "1159": "Impuestos pagados por anticipado",
    "11510": "Primas de Seguros pagados por anticipado",
    "12": "Activo no corriente",
    "121": "Inversiones y valores",
    "1211": "Inversiones en Bonos (mayor a un anio)",
    "1212": "Inversiones en Acciones",
    "1213": "Inversiones en negocios conjuntos",
    "1214": "Depositos a Plazo (mayor a 1 anio)",
    "122": "Propiedad planta y equipo",
    "1221": "Terrenos (para uso de la empresa)",
    "1222": "Edificios (para uso de la empresa)",
    "12221": "Depreciacion acumulada de edificio",
    "1223": "Maquinaria",
    "12231": "Depreciacion acumulada de maquinaria",
    "1224": "Mobiliario y equipo",
    "12241": "Depreciacion acumulada de mobiliario y equipo",
    "1225": "Vehiculos",
    "12251": "Depreciacion acumulada de vehiculos",
    "1226": "Equipos de transporte",
    "12261": "Depreciacion acumulada de equipos de transporte",
    "1227": "Equipos de reparto",
    "12271": "Depreciacion acumulada de equipos de reparto",
    "1228": "Herramientas",
    "12281": "Depreciacion acumulada de herramientas",
    "123": "Intangibles",
    "1231": "Plusvalia",
    "1232": "Derecho de autor",
    "1233": "Marca y Patente",
    "1234": "Licencias",
    "1235": "Programas Informaticos",
    "124": "Propiedades de Inversion",
    "1241": "Terrenos (para alquiler o venta)",
    "1242": "Edificios (para alquiler o venta)",
    "125": "Otros Activos",
    "1251": "Bancos (cuenta congelada)",
    "1252": "Documentos por Cobrar (largo plazo)",
    "1253": "Depositos en garantia",
    "2": "Pasivo",
    "21": "Pasivo Corriente",
    "211": "Cuentas y Documentos Por pagar",
    "2111": "Proveedores (Acreedores comerciales)",
    "2112": "Sueldos y salarios por pagar",
    "2113": "Impuestos por pagar",
    "2114": "Intereses por pagar",
    "2115": "Acreedores varios",
    "2116": "Documentos por pagar",
    "212": "Prestamos",
    "2121": "Prestamos bancarios",
    "2122": "Prestamos Hipotecarios",
    "213": "Provisiones",
    "2131": "Provisiones para compensaciones a empleados",
    "2132": "Provisiones para cubrir garantias a clientes",
    "2133": "Provisiones para cubrir reclamos legales",
    "214": "Cobros Anticipados",
    "2141": "Rentas cobradas por anticipado",
    "2142": "Intereses cobrados por anticipado",
    "2143": "Servicios cobrados por anticipado",
    "2144": "Suscripciones pagadas por anticipado",
    "2145": "Anticipos a clientes",
    "22": "Pasivo No Corriente",
    "221": "Cuentas y Documentos Por pagar",
    "2211": "Acreedores varios",
    "2212": "Documentos por pagar",
    "222": "Prestamos",
    "2221": "Prestamos bancarios",
    "2222": "Prestamos Hipotecarios",
    "223": "Provisiones",
    "2231": "Provisiones para compensaciones a empleados",
    "2232": "Provisiones para cubrir garantias a clientes",
    "2233": "Provisiones para cubrir reclamos legales",
    "224": "Cobros Anticipados",
    "2241": "Rentas cobradas por anticipado",
    "2242": "Intereses cobrados por anticipado",
    "2243": "Servicios cobrados por anticipado",
    "3": "Patrimonio Neto",
    "31": "Comerciante Individual",
    "311": "Capital",
    "312": "Resultados Acumulados",
    "3121": "Utilidades o perdidas de anios anteriores",
    "3122": "Utilidad o perdida neta del periodo",
    "32": "Empresa Juridica",
    "321": "Capital Social",
    "322": "Reservas",
    "3221": "Reserva Legal",
    "3222": "Reservas Estatuarias",
    "3223": "Reservas Voluntarias",
    "323": "Resultados Acumulados",
    "3231": "Utilidad o perdida de anios anteriores",
    "3232": "Utilidad o perdida neta del ejercicio",
    "4": "Divulgaciones",
}
